server:
  port: 8888
  
spring:
  application:
    name: uws-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared
  profiles:
    active: native

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 3
    instanceId: ${spring.application.name}:${server.port}
